### ISSUE TITLE
failure to predict - correct dependencies?

### ISSUE THREAD

**Issue by xanguera** [felixkreuk/UnsupSeg#3]
Hi,
I tried to install the software both in mac (using conda) and in a docker image installing all packages into the system.
When installing I am facing a problem with torchvision version 0.4.2 not being available for 1.4.0, I moved forward with torchvision 0.5.0 and all other dependencies installed correctly.

When trying to use the pretrained models I get the error below:

```python
python3 predict.py --ckpt /root/UnsupSeg/pretrained_models/buckeye+_pretrained.ckpt --wav /root/UnsupSeg/example_love.wav
running inference on: /root/UnsupSeg/example_love.wav
running inferece using ckpt: /root/UnsupSeg/pretrained_models/buckeye+_pretrained.ckpt


 ------------------------------------------------------------------------------------------
learning features from raw wav
prediction steps: [1]
Traceback (most recent call last):
  File "predict.py", line 55, in <module>
    main(args.wav, args.ckpt, args.prominence)
  File "predict.py", line 23, in main
    peak_detection_params = dill.loads(ckpt['peak_detection_params'])['cpc_1']
  File "/usr/local/lib/python3.8/dist-packages/dill/_dill.py", line 275, in loads
    return load(file, ignore, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/dill/_dill.py", line 270, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/usr/local/lib/python3.8/dist-packages/dill/_dill.py", line 472, in load
    obj = StockUnpickler.load(self)
TypeError: an integer is required (got type bytes)
```

**Comment by felixkreuk** [comment]
Hi Xavier, as I have not seen this error in previous issues, would you please try to use python 3.7? From a quick google search it seems that this issue might be related to python 3.8.

Thanks,
Felix

**Comment by xanguera** [comment]
Hi Felix,
thanks for your quick response. Using python 3.7 worked at the first try.
