### ISSUE TITLE
KeyError:  'Accessing unknown key in a struct: wd'

### ISSUE THREAD

**Issue by Taemra** [felixkreuk/UnsupSeg#4]
Hi @felixkreuk .

Thanks for your codes. I have been successfully used predict.py to get the phoneme boundaries, but I would like to train a new model on my own data so that the result may get better. I have configured the timit_path in the conf.yaml to my own datasets which has three sub directory (train/val/test), and did not change anything else in documents. 

Then using "python main.py" or "python main.py data=timit", I got the following error reports:

`Traceback (most recent call last):
  File "main.py", line 77, in <module>
    main()

  File "D:\anaconda\lib\site-packages\hydra\main.py", line 20, in decorated_main
    run_hydra(

  File "D:\anaconda\lib\site-packages\hydra\_internal\utils.py", line 171, in run_hydra
    hydra.run(

  File "D:\anaconda\lib\site-packages\hydra\_internal\hydra.py", line 82, in run
    return run_job(

  File "D:\anaconda\lib\site-packages\hydra\plugins\common\utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)

  File "main.py", line 28, in main
    cfg.wd = os.getcwd()

  File "D:\anaconda\lib\site-packages\omegaconf\dictconfig.py", line 73, in __setattr__
    self.__setitem__(key, value)

  File "D:\anaconda\lib\site-packages\omegaconf\dictconfig.py", line 40, in __setitem__
    raise KeyError(

KeyError: 'Accessing unknown key in a struct : wd'`

The problem may be very simple since I am not familiar with code-writing. But really hope to know how to use the main.py to train a model based on my own data.

**Comment by felixkreuk** [comment]
Hi @Taemra, could you please make sure you are using hydra version `hydra-core==0.11.3`? You can do that by running `pip intall hydra-core==0.11.3`. Let me know if this solves your error. Thanks.

**Comment by Taemra** [comment]
Hi Felix. It helps, the error is solved. Thank you very much. :D
